import{a as q,i,S as E}from"./assets/vendor-BK_rxH-O.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&a(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(t){if(t.ep)return;t.ep=!0;const n=o(t);fetch(t.href,n)}})();const b="https://pixabay.com/api/",P="51418093-89174c8449e8a26154b177f03";async function h(r,e){try{const o=await q.get(b,{params:{key:P,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40,page:e}});return o.data.hits.length===0&&i.error({message:"Sorry, there are no images matching your search query.",position:"topRight"}),{result:o.data.hits,totalHits:o.data.totalHits}}catch(o){i.error({title:"Error",message:"Something went wrong. Try again later",position:"topRight"}),console.error("Error: ",o)}}let d;function y(r){return r.map(e=>{let{largeImageURL:o,webformatURL:a,tags:t,likes:n,views:c,comments:v,downloads:S}=e;return`
      <a href="${o}" class="photo-card">
        <img src="${a}" alt="${t}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${n}</p>
          <p><strong>Views:</strong> ${c}</p>
          <p><strong>Comments:</strong> ${v}</p>
          <p><strong>Downloads:</strong> ${S}</p>
        </div>
      </a>
    `}).join("")}function w(){d?d.refresh():d=new E(".gallery a",{captionsData:"alt",captionDelay:150,animationSpeed:200,closeText:"×",navText:["<",">"]})}const R=document.querySelector(".search-form"),g=document.querySelector(".gallery"),p=document.querySelector(".loader-wrapper"),f=document.querySelector(".search-form input"),l=document.querySelector(".load-more"),s={query:"",page:1,total:null};R.addEventListener("submit",async r=>{if(r.preventDefault(),s.query=r.target.elements.searchQuery.value,s.page=1,!s.query){i.warning({message:"Please enter a search query",position:"topRight"});return}g.innerHTML="",m(p),f.classList.add("active");try{const{result:e,totalHits:o}=await h(s.query,s.page);if(e.length===0){u(l);return}const a=y(e);g.innerHTML=a,s.total=o,w(),L()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{u(p),f.classList.remove("active")}});l.addEventListener("click",async r=>{m(p);try{u(l),s.page+=1;const{result:e}=await h(s.query,s.page),o=y(e);g.insertAdjacentHTML("beforeend",o),L(),w(),x()}catch(e){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{u(p)}});function L(){const e=Math.ceil(s.total/40);s.page>=e?(u(l),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m(l)}function m(r){r.classList.remove("hidden")}function u(r){r.classList.add("hidden")}function x(){const e=g.firstElementChild.getBoundingClientRect().height*2;window.scrollBy({behavior:"smooth",top:e})}
//# sourceMappingURL=index.js.map
