import{a as L,i as a,S}from"./assets/vendor-BK_rxH-O.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))c(o);new MutationObserver(o=>{for(const n of o)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&c(g)}).observe(document,{childList:!0,subtree:!0});function t(o){const n={};return o.integrity&&(n.integrity=o.integrity),o.referrerPolicy&&(n.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?n.credentials="include":o.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function c(o){if(o.ep)return;o.ep=!0;const n=t(o);fetch(o.href,n)}})();const q="https://pixabay.com/api/",v="51418093-89174c8449e8a26154b177f03",E=15;async function h(e,r){try{const{data:t}=await L.get(q,{params:{key:v,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:E,page:r}});return(t.totalHits===0||t.hits.length===0)&&a.error({message:"Sorry, there are no images matching your search query.",position:"topRight"}),{result:t.hits,totalHits:t.totalHits}}catch(t){throw a.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"}),t}}let p;function y(e){const r=e.map(t=>`
      <a href="${t.largeImageURL}" class="photo-card">
        <img src="${t.webformatURL}" alt="${t.tags}" loading="lazy" />
        <div class="info">
          <p><strong>Likes:</strong> ${t.likes}</p>
          <p><strong>Views:</strong> ${t.views}</p>
          <p><strong>Comments:</strong> ${t.comments}</p>
          <p><strong>Downloads:</strong> ${t.downloads}</p>
        </div>
      </a>
    `).join("");document.querySelector(".gallery").insertAdjacentHTML("beforeend",r),p?p.refresh():p=new S(".gallery a",{captionsData:"alt",captionDelay:150,animationSpeed:200,closeText:"×",navText:["<",">"]})}function P(){document.querySelector(".gallery").innerHTML=""}function m(e){e.classList.remove("hidden")}function l(e){e.classList.add("hidden")}function b(){const e=document.querySelector(".gallery a");if(!e)return;const r=e.getBoundingClientRect().height*2;window.scrollBy({top:r,behavior:"smooth"})}function w(e,r){const c=Math.ceil(e.total/40);e.page>=c?(l(r),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):m(r)}const d=document.querySelector(".form");document.querySelector(".gallery");const u=document.querySelector(".loader-wrapper"),f=document.querySelector(".form input"),i=document.querySelector(".load-more"),s={query:"",page:1,total:null};d.addEventListener("submit",async e=>{if(e.preventDefault(),s.query=e.target.elements.searchQuery.value.trim(),s.page=1,!s.query){a.warning({message:"Please enter a search query",position:"topRight"});return}P(),m(u),f.classList.add("active");try{const{result:r,totalHits:t}=await h(s.query,s.page);if(r.length===0){l(i);return}y(r),s.total=t,w(s,i)}catch(r){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",r)}finally{d.searchQuery.value="",l(u),f.classList.remove("active")}});i.addEventListener("click",async()=>{m(u);try{l(i),s.page+=1;const{result:e}=await h(s.query,s.page);y(e),w(s,i),b()}catch(e){a.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error("Error",e)}finally{l(u)}});
//# sourceMappingURL=index.js.map
